### ISSUE TITLE
SM2 Algorithm: Incorrect Interval Calculation for Higher Box Numbers

### ISSUE THREAD

**Issue by benjaminhouy** [jaysonvirissimo/active_recall#31]
## Description

The current implementation of the SM2 algorithm in the `ActiveRecord::SM2` class is not correctly calculating intervals for cards that have been reviewed correctly multiple times (i.e., cards in higher box numbers). This results in unexpectedly short intervals between reviews for well-known cards.

## Steps to Reproduce

Create a new flashcard
Review the card correctly multiple times (at least 7)
Observe that the next review date is much closer than expected for a well-known card

## Example

A card with the following attributes:

box: 7
times_right: 7
easiness_factor: 2.46
last_reviewed: "2024-08-21"

Has a next_review date of "2024-09-05", which is only about 2 weeks later. With correct exponential growth, this interval should be much longer, potentially several months.

## Proposed solution

I believe changing the interval calculation to the following would be more in line with SM2 and result in longer intervals:

```
6 * (@easiness_factor ** (@box - 1))
```

**Comment by jaysonvirissimo** [comment]
I merged https://github.com/jaysonvirissimo/active_recall/pull/32, since I agree that the existing behavior wasn't faithful to the real SM-2 algorithm, but the specs were failing, so started to rewrite them [here](https://github.com/jaysonvirissimo/active_recall/pull/33), but that uncovered a few more inaccuracies. Will close this issue once those other inaccuracies are dealt with before cutting a new version of the gem.

**Comment by jaysonvirissimo** [comment]
Fixed in version [2.1.0](https://github.com/jaysonvirissimo/active_recall/releases/tag/v2.1.0).
